version: "3.1"

services:

  jcc_app:
    container_name: jcc_app
    restart: unless-stopped
    env_file: ../.env
    build:
      context: ../
      dockerfile: ./.dockers/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ../src:/app/src
      - ../uploads:/app/uploads
    depends_on:
      jcc_db:
        condition: service_started

  jcc_db:
    image: postgres:15.2
    container_name: jcc_db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: jcc
      TZ: America/Hermosillo
    volumes:
      - ../DB/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  jcc_adminer:
    image: adminer
    container_name: jcc_adminer
    environment:
      TZ: America/Hermosillo
      ADMINER_DESIGN: "ng9"
    ports:
      - 8080:8080
    depends_on:
      jcc_db:
        condition: service_started